"""
Comprehensive verification of extracted output (module version).
"""

import warnings
import pandas as pd
from pathlib import Path

warnings.filterwarnings("ignore", category=FutureWarning)

# Expected 14 components across both sources
EXPECTED_COMPONENTS = {
    "Tower Shell",
    "Tower Internals",
    "Anchor cage",
    "Tower Bolts Set",
    "Steel Tower Quality Inspectors",
    "Option Coating c4/c5",
    "Option Anchor Cage: German requirements for NAT AC",
    "Option hybrid tower: MB Monthly Cost Indexation",
    "Option hybrid tower: white coating of concrete part",
    "Option hybrid tower: no red stripe on concrete part",
    "Foundations",
    "Concrete Tower Logistics",
    "Concrete Tower Keystones + Internals",
    "Concrete Tower C&I",
}

# Hardcoded spot checks for reference tower — only years 2026-2028
REFERENCE_TOWER = "Tower N117/3000 Controlled IEC2a TS76 TiT 50Hz NCV"
SPOT_CHECK_DATA = [
    ("Tower Shell", 2026, "Europe", 255993.398875, None),
    ("Tower Shell", 2026, "Asia", 45753.257325, 131977.1933106),
    ("Tower Shell", 2027, "Europe", 263120.80772125, None),
    ("Tower Shell", 2028, "Europe", 276276.8481073125, None),
    ("Tower Shell", 2026, "Germany", 290195.32807609043, None),
    ("Tower Internals", 2026, "Europe", 151000, None),
    ("Tower Bolts Set", 2026, "Europe", 3637.636325503345, None),
    ("Steel Tower Quality Inspectors", 2026, "Europe", 1950, None),
    ("Steel Tower Quality Inspectors", 2026, "US", None, 5519.999999999999),
    ("Option Coating c4/c5", 2026, "Europe", 5000, None),
]


def run_verification(
    output_path: Path | str,
    selected_years: list[int],
    canonical_regions: list[str],
    log_callback=None,
) -> dict:
    """
    Verify extracted output file.

    Args:
        output_path: Path to output Excel file generated by extractor
        selected_years: List of years that were used in extraction [2026, 2027, ...]
        canonical_regions: List of canonical region names
        log_callback: fn(msg: str) for logging to UI

    Returns:
        dict with keys: results (list of tuples), exit_code, pass_count, fail_count
    """
    def _log(msg: str):
        if log_callback:
            log_callback(msg)
        else:
            print(msg)

    output_path = Path(output_path)

    # Load the output file
    _log(f"Leyendo {output_path}...")
    df = pd.read_excel(str(output_path))

    # Convert Cost columns to numeric
    df = df.copy()
    df["Cost_Currency1"] = pd.to_numeric(df["Cost_Currency1"], errors="coerce")
    df["Cost_Currency2"] = pd.to_numeric(df["Cost_Currency2"], errors="coerce")

    # Validation results: list of (section, status, message)
    results = []

    # --- 1. Schema validation ---
    expected_cols = [
        "Component_Category", "Component", "Key", "Brand",
        "Year_Production", "Region", "Cost_Currency1", "Cost_Currency2"
    ]
    cols_ok = all(col in df.columns for col in expected_cols)
    if cols_ok:
        results.append(("SCHEMA", "OK", f"8 columnas | {len(df):,} filas"))
    else:
        missing = [c for c in expected_cols if c not in df.columns]
        results.append(("SCHEMA", "FAIL", f"Columnas faltantes: {missing}"))

    # --- 2. Dtypes ---
    dtype_ok = True
    dtype_msgs = []
    if df["Year_Production"].dtype not in ["int64", "Int64"]:
        dtype_ok = False
        dtype_msgs.append(f"Year_Production={df['Year_Production'].dtype}")
    if df["Cost_Currency1"].dtype != "float64":
        dtype_ok = False
        dtype_msgs.append(f"Cost_Currency1={df['Cost_Currency1'].dtype}")
    if df["Cost_Currency2"].dtype != "float64":
        dtype_ok = False
        dtype_msgs.append(f"Cost_Currency2={df['Cost_Currency2'].dtype}")

    if dtype_ok:
        results.append(("DTYPES", "OK", "Year_Production=int64 | C1=float64 | C2=float64"))
    else:
        results.append(("DTYPES", "FAIL", " | ".join(dtype_msgs)))

    # --- 3. Row count (dynamic) ---
    if sorted(selected_years) == [2026, 2027, 2028]:
        expected_rows = 133588
        row_count_ok = len(df) == expected_rows
        status = "FAIL" if not row_count_ok else "OK"
        results.append(("ROW_COUNT", status, f"{len(df):,} filas"))
    else:
        # Non-standard year selection — can't verify against fixed reference
        results.append(("ROW_COUNT", "WARN", f"{len(df):,} filas (años no estándar: {sorted(selected_years)})"))

    # --- 4. Null integrity ---
    critical_cols = ["Key", "Brand", "Component_Category", "Component", "Region", "Year_Production"]
    null_counts = {col: df[col].isna().sum() for col in critical_cols}
    nulls_ok = all(count == 0 for count in null_counts.values())
    if nulls_ok:
        results.append(("NULLS", "OK", "Sin nulos en columnas clave"))
    else:
        null_details = [f"{col}={count}" for col, count in null_counts.items() if count > 0]
        results.append(("NULLS", "FAIL", " | ".join(null_details)))

    # --- 5. Year domain ---
    found_years = set(int(y) for y in df["Year_Production"].dropna().unique())
    selected_years_set = set(selected_years)
    years_ok = found_years == selected_years_set
    if years_ok:
        results.append(("YEARS", "OK", f"Años válidos: {sorted(selected_years)}"))
    else:
        extra = found_years - selected_years_set
        missing = selected_years_set - found_years
        diff = []
        if extra:
            diff.append(f"Extra={extra}")
        if missing:
            diff.append(f"Faltantes={missing}")
        results.append(("YEARS", "FAIL", " | ".join(diff)))

    # --- 6. Region domain ---
    canonical_regions_set = set(canonical_regions)
    found_regions = set(df["Region"].dropna().unique())
    regions_ok = found_regions == canonical_regions_set
    if regions_ok:
        results.append(("REGIONS", "OK", f"{len(found_regions)}/11 regiones canónicas encontradas"))
    else:
        extra = found_regions - canonical_regions_set
        missing = canonical_regions_set - found_regions
        diff = []
        if extra:
            diff.append(f"Extra={len(extra)}")
        if missing:
            diff.append(f"Faltantes={len(missing)}")
        results.append(("REGIONS", "FAIL", " | ".join(diff)))

    # --- 7. Component_Category always "Tower" ---
    comp_cat_ok = (df["Component_Category"] == "Tower").all()
    if comp_cat_ok:
        results.append(("COMPONENT_CATEGORY", "OK", 'Siempre "Tower"'))
    else:
        bad_count = (df["Component_Category"] != "Tower").sum()
        results.append(("COMPONENT_CATEGORY", "FAIL", f"{bad_count} filas != Tower"))

    # --- 8. Component coverage ---
    found_components = set(df["Component"].unique())
    components_ok = found_components == EXPECTED_COMPONENTS
    if components_ok:
        results.append(("COMPONENTS", "OK", f"14/14 componentes encontrados"))
    else:
        extra = found_components - EXPECTED_COMPONENTS
        missing = EXPECTED_COMPONENTS - found_components
        diff = []
        if extra:
            diff.append(f"Extra={len(extra)}")
        if missing:
            diff.append(f"Faltantes={len(missing)}")
        results.append(("COMPONENTS", "FAIL", " | ".join(diff)))

    # --- 9. No duplicates ---
    merge_keys = ["Component", "Key", "Brand", "Year_Production", "Region"]
    dups = df.duplicated(subset=merge_keys, keep=False)
    dup_count = dups.sum()
    if dup_count == 0:
        results.append(("DUPLICATES", "OK", "Sin filas duplicadas"))
    else:
        results.append(("DUPLICATES", "WARN", f"{dup_count} filas duplicadas"))

    # --- 10. Cost sanity ---
    c1_non_null = df["Cost_Currency1"].dropna()
    c2_non_null = df["Cost_Currency2"].dropna()
    c1_bad = (c1_non_null <= 0).sum() if len(c1_non_null) > 0 else 0
    c2_bad = (c2_non_null <= 0).sum() if len(c2_non_null) > 0 else 0
    cost_issues = c1_bad + c2_bad
    if cost_issues == 0:
        results.append(("COST_SANITY", "OK", "Todos los costos > 0"))
    else:
        problems = []
        if c1_bad > 0:
            problems.append(f"C1<=0: {c1_bad}")
        if c2_bad > 0:
            problems.append(f"C2<=0: {c2_bad}")
        results.append(("COST_SANITY", "WARN", " | ".join(problems)))

    # --- 11. Spot checks (conditional on year availability) ---
    spot_checks_passed = 0
    spot_checks_failed = 0
    spot_check_details = []
    spot_checks_skipped = 0

    for comp, year, region, expected_c1, expected_c2 in SPOT_CHECK_DATA:
        # Only run spot check if the year is in selected_years
        if year not in selected_years:
            spot_checks_skipped += 1
            continue

        mask = (
            (df["Key"] == REFERENCE_TOWER)
            & (df["Component"] == comp)
            & (df["Year_Production"] == year)
            & (df["Region"] == region)
        )
        rows = df[mask]
        if len(rows) == 0:
            spot_checks_failed += 1
            spot_check_details.append(f"✗ {comp}/{year}/{region}: NOT FOUND")
            continue

        r = rows.iloc[0]
        c1 = r["Cost_Currency1"]
        c2 = r["Cost_Currency2"]

        c1_ok = True
        c2_ok = True

        if expected_c1 is not None:
            c1_ok = abs(float(c1) - expected_c1) < 0.01 if pd.notna(c1) else False

        if expected_c2 is not None:
            c2_ok = abs(float(c2) - expected_c2) < 0.01 if pd.notna(c2) else False

        if c1_ok and c2_ok:
            spot_checks_passed += 1
        else:
            spot_checks_failed += 1
            problem = []
            if not c1_ok:
                problem.append("C1 mismatch")
            if not c2_ok:
                problem.append("C2 mismatch")
            spot_check_details.append(f"✗ {comp}/{year}/{region}: {', '.join(problem)}")

    total_spot_checks = len(SPOT_CHECK_DATA) - spot_checks_skipped
    if spot_checks_failed == 0:
        status = "OK" if total_spot_checks > 0 else "INFO"
        msg = f"{spot_checks_passed}/{total_spot_checks} checks pasados"
        if spot_checks_skipped > 0:
            msg += f" ({spot_checks_skipped} skipped)"
        results.append(("SPOT_CHECKS", status, msg))
    else:
        results.append(("SPOT_CHECKS", "FAIL", f"{spot_checks_passed} pasados, {spot_checks_failed} fallidos"))

    # --- 12. Gap summary ---
    gaps = df[(df["Cost_Currency1"].isna()) & (df["Cost_Currency2"].isna())]
    gap_count = len(gaps)
    results.append(("GAPS", "INFO", f"{gap_count:,} filas sin costo (C1 y C2 null)"))

    # Print results
    _log("\n" + "=" * 60)
    _log("VERIFICATION REPORT")
    _log("=" * 60 + "\n")

    # Collect counts
    pass_count = sum(1 for _, status, _ in results if status == "OK")
    fail_count = sum(1 for _, status, _ in results if status == "FAIL")
    warn_count = sum(1 for _, status, _ in results if status == "WARN")

    # Print each result
    for section, status, msg in results:
        status_str = f"[{status}]".ljust(7)
        section_str = f"[{section}]".ljust(18)
        _log(f"{section_str} {status_str} {msg}")

    # Print spot check details if any failed
    if spot_check_details:
        _log("")
        for detail in spot_check_details:
            _log(f"  {detail}")

    # Final result line
    _log("\n" + "-" * 60)
    if fail_count == 0:
        status_summary = f"{pass_count}/11 checks OK"
        if warn_count > 0:
            status_summary += f" | {warn_count} advertencia(s)"
        final = f"RESULTADO FINAL: PASS  —  {status_summary}"
        _log(final)
        exit_code = 0
    else:
        final = f"RESULTADO FINAL: FAIL  —  {fail_count} error(es) detectado(s)"
        _log(final)
        exit_code = 1

    _log("=" * 60 + "\n")

    return {
        "results": results,
        "exit_code": exit_code,
        "pass_count": pass_count,
        "fail_count": fail_count,
        "spot_check_details": spot_check_details,
    }
